services:
  frontend:
    image: node:24-alpine
    volumes:
      - '.:/app'
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
    command: [ 'npm', 'run', 'dev' ]
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - .env
    working_dir: /app
    networks:
      - caddie_network
    tty: true        # Add this
    stdin_open: true # Add this

networks:
  caddie_network:
    external: true